spring:
  profiles:
#    开发环境，配置文件由nacos管理
    active: dev

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
  httpclient:
    enabled: true

logging:
  level:
    com.web.service.CustomerService: debug

ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000