server:
  port: 8323


spring:
  application:
    name: zhou-test
  cloud:
    nacos:
      discovery:
        server-addr: 101.201.66.127:8082
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

logging:
  level:
    com.test.service.CustomerService: debug

#请求超时时间
ribbon:
  ReadTimeout:  8000
  ConnectTimeout: 8000